/**************************************************************************
 * C S 429 system emulator
 * 
 * instr_Decode.c - Decode stage of instruction processing pipeline.
 **************************************************************************/ 

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <assert.h>
#include "err_handler.h"
#include "instr.h"
#include "instr_pipeline.h"
#include "forward.h"
#include "machine.h"
#include "hw_elts.h"

#define SP_NUM 31
#define XZR_NUM 32

extern machine_t guest;
extern mem_status_t dmem_status;

extern int64_t W_wval;

/*
 * Control signals for D, X, M, and W stages.
 * Generated by D stage logic.
 * D control signals are consumed locally. 
 * Others must be buffered in pipeline registers.
 * STUDENT TO-DO:
 * Generate the correct control signals for this instruction's
 * future stages and write them to the corresponding struct.
 */

static comb_logic_t 
generate_DXMW_control(opcode_t op,
                      d_ctl_sigs_t *D_sigs, x_ctl_sigs_t *X_sigs, m_ctl_sigs_t *M_sigs, w_ctl_sigs_t *W_sigs) {
    D_sigs->src2_sel = false;
    X_sigs->valb_sel = false;
    X_sigs->set_CC = false;
    M_sigs->dmem_read = false;
    M_sigs->dmem_write = false;
    W_sigs->dst_sel = false;
    W_sigs->wval_sel = false;
    W_sigs->w_enable = false;

    M_sigs->dmem_read = (op == OP_LDUR);
    M_sigs->dmem_write = (op == OP_STUR);

    W_sigs->w_enable = !((op == OP_STUR) || (op == OP_B) || (op == OP_B_COND) || (op == OP_RET)
        || (op == OP_NOP) || (op == OP_HLT) || (op == OP_CMP_RR) || (op == OP_TST_RR));

    W_sigs->wval_sel = (op == OP_LDUR);

    X_sigs->valb_sel = (op == OP_ADDS_RR) || (op == OP_ANDS_RR) || 
                       (op == OP_SUBS_RR)|| (op == OP_CMP_RR) || (op == OP_TST_RR) || (op == OP_ORR_RR) ||
                       (op == OP_EOR_RR);

    X_sigs->set_CC = (op == OP_ADDS_RR) || (op == OP_SUBS_RR) || (op == OP_ANDS_RR) || (op == OP_CMP_RR) || (op == OP_TST_RR);

    D_sigs->src2_sel = (op == OP_STUR);

    W_sigs->dst_sel = (op == OP_BL);
}

/*
 * Logic for extracting the immediate value for M-, I-, and RI-format instructions.
 * STUDENT TO-DO:
 * Extract the immediate value and write it to *imm.
 */

static comb_logic_t 
extract_immval(uint32_t insnbits, opcode_t op, int64_t *imm) {
    *imm = 0;  

    switch (op) {
        case OP_STUR:
        case OP_LDUR:
            *imm = bitfield_s64(insnbits, 12, 9);
            break;
        case OP_MOVK:
        case OP_MOVZ:
            *imm = bitfield_u32(insnbits, 5, 16);
            break;
        case OP_B_COND:
        case OP_ADRP:
            *imm = bitfield_s64(insnbits, 5, 19);
            break;
        case OP_ADD_RI:
        case OP_SUB_RI:
        case OP_LSL:
        case OP_LSR:
        case OP_ASR:
            *imm = bitfield_u32(insnbits, 10, 12);
            break;
        case OP_B:
        case OP_BL:
            *imm = bitfield_s64(insnbits, 0, 26);
            break;
        default:
            break;
    }
}

/*
 * Logic for determining the ALU operation needed for this opcode.
 * STUDENT TO-DO:
 * Determine the ALU operation based on the given opcode
 * and write it to *ALU_op.
 */
static comb_logic_t
decide_alu_op(opcode_t op, alu_op_t *ALU_op) {
    switch (op) {
        case OP_ADD_RI:
        case OP_ADDS_RR:
            *ALU_op = PLUS_OP;
            break;
        case OP_SUB_RI:
        case OP_SUBS_RR:
            *ALU_op = MINUS_OP;
            break;
        case OP_MVN:
            *ALU_op = INV_OP;
            break;
        case OP_ORR_RR:
            *ALU_op = OR_OP;
            break;
        case OP_EOR_RR:
            *ALU_op = EOR_OP;
            break;
        case OP_ANDS_RR:
            *ALU_op = AND_OP;
            break;
        case OP_MOVK:
        case OP_MOVZ:
            *ALU_op = MOV_OP;
            break;
        case OP_LSL:
            *ALU_op = LSL_OP;
            break;
        case OP_LSR:
            *ALU_op = LSR_OP;
            break;
        case OP_ASR:
            *ALU_op = ASR_OP;
            break;
        case OP_CSEL:
            *ALU_op = CSEL_OP;
            break;
        case OP_CSINV:
            *ALU_op = CSINV_OP;
            break;
        case OP_CSINC:
            *ALU_op = CSINC_OP;
            break;
        case OP_CSNEG:
            *ALU_op = CSNEG_OP;
            break;
        case OP_CBZ:
            *ALU_op = CBZ_OP;
            break;
        case OP_CBNZ:
            *ALU_op = CBNZ_OP;
            break;
        default:
            *ALU_op = PASS_A_OP;
            break;
    }
}

/*
 * Utility functions for copying over control signals across a stage.
 * STUDENT TO-DO:
 * Copy the input signals from the input side of the pipeline
 * register to the output side of the register.
 */

comb_logic_t 
copy_m_ctl_sigs(m_ctl_sigs_t *dest, m_ctl_sigs_t *src) {
    dest->dmem_read = src->dmem_read;
    dest->dmem_write = src->dmem_write;
}

comb_logic_t 
copy_w_ctl_sigs(w_ctl_sigs_t *dest, w_ctl_sigs_t *src) {
    dest->dst_sel = src->dst_sel;
    dest->wval_sel = src->wval_sel;
    dest->w_enable = src->w_enable;
}

comb_logic_t
extract_regs(uint32_t insnbits, opcode_t op, 
             uint8_t *src1, uint8_t *src2, uint8_t *dst) {
    
    //rn is first src, starts at 5 and goes 5 across. if not movz, nop, hlt, then get src 1 to be this bit field u 32, 
    //if u read in a 31, need to know if u interpret it as the stack pointer or the xzr. if it is xzr, 
    //left ops, interpret as stack pointer, and everything else is xzr

    if (!(op == OP_MOVZ || op == OP_NOP || op == OP_HLT || 
          op == OP_MOVK || op == OP_ADRP || op == OP_RET ||
          op == OP_B_COND || op == OP_B || op == OP_BL)){
        *src1 = (uint8_t *) bitfield_u32(insnbits, 5, 5);
    }
    // includes LDUR, STUR, 
    //added mvn which was not in old implementation
    if (op == OP_ADDS_RR || op == OP_SUBS_RR || op == OP_CMP_RR ||
        op == OP_ORR_RR || op == OP_EOR_RR || op == OP_ANDS_RR ||
        op == OP_TST_RR || op == OP_MVN){
        *src2 = (uint8_t *) bitfield_u32(insnbits, 16, 5);
    }
    if (op != OP_RET){
        *dst = (uint8_t *) bitfield_u32(insnbits, 0, 5);
    }
    if (op == OP_RET){
        *src1 = (uint8_t *) bitfield_u32(insnbits, 5, 5);
    }
    if (op == OP_MOVK){
        *src1 = *dst;
    }
    //error checking of registers being SP
    if (*src1 == SP_NUM || *src2 == SP_NUM || *dst == SP_NUM){
        if (!(op == OP_LDUR || op == OP_STUR || op == OP_ADD_RI || op == OP_SUB_RI)){
            if (*src1 == SP_NUM){
                *src1 = XZR_NUM;
            }
            if(*src2 == SP_NUM){
                *src2 = XZR_NUM;
            }
            if(*dst == SP_NUM){
                *dst = XZR_NUM;
            }
        }
        if (op == OP_LDUR || op == OP_STUR){
            if (*src2 == SP_NUM){
                *src2 = XZR_NUM;
            }
            if(*dst == SP_NUM){
                *dst = XZR_NUM;
            }
        }
        
    }

    //RET only has src1, as dst is always 30
    // else if(op == OP_RET){
    //     dst = bitfield_u32(dst, 5, 5);
    // }

    //old implementation
    // *src1 = 0;
    // *src2 = 0;
    // *dst = 0;

    // if (op == OP_ADDS_RR || op == OP_SUBS_RR || op == OP_CMP_RR ||
    //     op == OP_ORR_RR || op == OP_EOR_RR || op == OP_ANDS_RR ||
    //     op == OP_TST_RR) {
    //     *src1 = (insnbits >> 5) & 0x1F;  
    //     *src2 = (insnbits >> 16) & 0x1F;
    //     *dst = insnbits & 0x1F;          
    // }
    // else if (op == OP_ADD_RI || op == OP_SUB_RI || op == OP_LSL ||
    //          op == OP_LSR || op == OP_ASR || op == OP_UBFM || op == OP_LDUR ||
    //          op == OP_STUR) {
    //     *src1 = (insnbits >> 5) & 0x1F;  
    //     *dst = insnbits & 0x1F;  
    // }
    // else if (op == OP_RET) {
    //     *src1 = (insnbits >> 5) & 0x1F;  
    // } 
    // else {
    //     *src1 = 0;
    //     *src2 = 0;
    //     *dst = 0;
    // }
}

/*
 * Decode stage logic.
 * STUDENT TO-DO:
 * Implement the decode stage.
 * 
 * Use `in` as the input pipeline register,
 * and update the `out` pipeline register as output.
 * Additionally, make sure the register file is updated
 * with W_out's output when you call it in this stage.
 * 
 * You will also need the following helper functions:
 * generate_DXMW_control, regfile, extract_immval,
 * and decide_alu_op.
 */

comb_logic_t decode_instr(d_instr_impl_t *in, x_instr_impl_t *out) {
    d_ctl_sigs_t local_D_sigs;
    x_ctl_sigs_t local_X_sigs;
    m_ctl_sigs_t local_M_sigs;
    w_ctl_sigs_t local_W_sigs;

    generate_DXMW_control(in->op, &local_D_sigs, &local_X_sigs, &local_M_sigs, &local_W_sigs);

    out->X_sigs = local_X_sigs;
    out->M_sigs = local_M_sigs;
    out->W_sigs = local_W_sigs;

    uint8_t src1, src2, dst;
    src1 = 0;
    src2 = 0; 
    dst = 0;
    extract_regs(in->insnbits, in->op, &src1, &src2, &dst);
    regfile(src1, src2, W_out->dst, W_wval, W_out->W_sigs.w_enable, &out->val_a, &out->val_b);
    decide_alu_op(in->op, &out->ALU_op);
    extract_immval(in->insnbits, in->op, &out->val_imm);
    out->dst = dst;
    out->op = in->op;
    out->print_op = in->print_op; 
    out->seq_succ_PC = in->seq_succ_PC; 
    out->status = in->status;
    if (in->op == OP_MOVZ){
        out->val_a = 0;
        out->val_hw = bitfield_u32(in->insnbits, 21, 2) << 4;
    }
    else if (in->op == OP_MOVK){
        out->val_hw = bitfield_u32(in->insnbits, 21, 2) << 4;
    }
    else {
        out->val_hw = 0;
    }

}
